name: Format

on:
  pull_request:
    branches: [ "main" ]    

jobs:
    
  format:
    name: Formatting Swift files
    runs-on: macos-latest
    
    steps:
      - name: Installing formatter
        run: |
          brew install swiftformat
          brew upgrade swiftformat
    
      - name: Repository checkout
        uses: actions/checkout@v3
    
      - name: Formatting files
        run: swiftformat . --swiftversion 5.7.2
      
      - name: Adding empty line @ EOF
        run: find $(pwd) -type f -name "*.swift" -exec bash -c "[ -n 'tail -c1 {}' ] && printf '\n' >>{}" \;
      
      - name: Pushing changes
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            if [[ $(git diff --shortstat | grep 'changed') ]]; then git commit -m "Automated formatting" ; git push ; fi
